---
- hosts: workstation
  gather_facts: true
  tasks:
    #- name: create bin directory
      #file:
        #path: /root/bin
        #state: directory
        #force: yes
    - name: List Files
      shell: "ls -ltr"
     
    - name: Hostname
      shell: "hostname"
     
    - name: get script common.sh
      get_url:
        url: "{{ param_repo_base }}/scripts/common.sh"
        dest: /tmp/
        #dest: /root/bin/
        mode: 0755
        use_proxy: no

    - name: get script jq
      get_url: 
        url: "{{ param_repo_base }}/scripts/jq-linux64"
        dest: /root/bin/jq
        mode: 0755
    - name: get script order_svc.sh
      get_url:
        url: "{{ param_repo_base }}/scripts/order_svc.sh"
        dest: /root/order_svc.sh
        mode: 0755
    - name: create credentials
      copy:
        content: |
          export username={{ param_user }}
          export password={{ param_password }}
          export uri=https://labs.opentlc.com
        dest: /root/credential.rc
        mode: 0755

    # Fix the existing shell scripts to reference jq command with bin/jq
    - name: fix scripts
      shell: "sed -i 's/ jq/ bin\\/jq/g' {{ item }}"
      with_items:
        - /root/common.sh
        - /root/order_svc.sh

    # Using this script will always deploy environments in the us-east-1 region.
    # TODO: this shell task is not working yet!
    - name: order service on opentlc
      shell: source /root/credential.rc; ./order_svc.sh -y -c 'OPENTLC Automation' -i 'Ansible Advanced - Three Tier App' -t 1 -d 'dialog_expiration=7;region=na;nodes=1;dialog_runtime=8;notes=Training - As part of course'
      args:
        chdir: /root
    - name: Wait for mail
      pause:
        minutes: 10 
