- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      region_name: "{{ openstack_region | default('regionOne') }}"
    register: r_instances
    
  - debug: var=r_instances
  
  - meta: end_play

  - name: Curl website
    uri:
      url: "http://{{ item }}"
      return_content: yes
    register: webpage
    with_items:
      - "{{ groups['frontends'] }}"
    
  
  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in item.content"
    #when: webpage.status!=200
    with_items: "{{ webpage.results }}"
    tags:
      - osp.smoke
